//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.WCFServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServer.ICalculatorServer")]
    public interface ICalculatorServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorServer/PerformAddition", ReplyAction="http://tempuri.org/ICalculatorServer/PerformAdditionResponse")]
        int PerformAddition(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorServer/PerformMultiplcation", ReplyAction="http://tempuri.org/ICalculatorServer/PerformMultiplcationResponse")]
        int PerformMultiplcation(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorServer/PerformSubtraction", ReplyAction="http://tempuri.org/ICalculatorServer/PerformSubtractionResponse")]
        int PerformSubtraction(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorServer/PerformDivision", ReplyAction="http://tempuri.org/ICalculatorServer/PerformDivisionResponse")]
        float PerformDivision(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServerChannel : ServiceClient.WCFServer.ICalculatorServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServerClient : System.ServiceModel.ClientBase<ServiceClient.WCFServer.ICalculatorServer>, ServiceClient.WCFServer.ICalculatorServer {
        
        public CalculatorServerClient() {
        }
        
        public CalculatorServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int PerformAddition(int x, int y) {
            return base.Channel.PerformAddition(x, y);
        }
        
        public int PerformMultiplcation(int x, int y) {
            return base.Channel.PerformMultiplcation(x, y);
        }
        
        public int PerformSubtraction(int x, int y) {
            return base.Channel.PerformSubtraction(x, y);
        }
        
        public float PerformDivision(int x, int y) {
            return base.Channel.PerformDivision(x, y);
        }
    }
}
